/**
 * @module app/seed/decorator-links
 * @description Runtime registry of the authored `assets/data/decorator-links.json`
 * asset (generated by the content pipeline): every `@decorator` token found in the
 * features/modules content maps to its deployed documentation page in the decorator's
 * original repository. The {@link app/components/MarkdownPipe} consumes this registry
 * to turn `@decorator` tokens in prose into documentation links.
 */

/**
 * @description One decorator entry of the authored `assets/data/decorator-links.json`.
 * @interface DecoratorLink
 * @memberOf module:app/seed/decorator-links
 */
export interface DecoratorLink {
  repo?: string;
  kind?: string;
  url?: string;
  en?: string;
  pt?: string;
}

/**
 * @description Shape of the authored `assets/data/decorator-links.json` asset.
 * @interface DecoratorLinksAsset
 * @memberOf module:app/seed/decorator-links
 */
export interface DecoratorLinksAsset {
  decorators?: Record<string, DecoratorLink>;
  excluded?: Record<string, string>;
}

/**
 * @description Module-scope registry of decorator token -> documentation link.
 * @type {Record<string, DecoratorLink>}
 * @memberOf module:app/seed/decorator-links
 */
let DECORATOR_LINKS: Record<string, DecoratorLink> = {};

/**
 * @description Replaces the in-memory decorator link registry.
 * @function setDecoratorLinks
 * @param {Record<string, DecoratorLink>} links - The authored token -> link map.
 * @returns {void}
 * @memberOf module:app/seed/decorator-links
 */
export function setDecoratorLinks(links: Record<string, DecoratorLink>): void {
  DECORATOR_LINKS = links || {};
}

/**
 * @description Reads the current decorator link registry.
 * @function getDecoratorLinks
 * @returns {Record<string, DecoratorLink>} The token -> link map.
 * @memberOf module:app/seed/decorator-links
 */
export function getDecoratorLinks(): Record<string, DecoratorLink> {
  return DECORATOR_LINKS;
}

/**
 * @description Resolves the documentation link of a decorator token.
 * @function resolveDecoratorLink
 * @param {string} token - The `@decorator` token (including the leading `@`).
 * @returns {DecoratorLink|undefined} The authored link, else `undefined`.
 * @memberOf module:app/seed/decorator-links
 */
export function resolveDecoratorLink(token: string): DecoratorLink | undefined {
  return DECORATOR_LINKS[token];
}

/**
 * @description Loads the authored decorator link asset into the registry.
 * @summary Fetches `assets/data/decorator-links.json` once and stores its
 * `decorators` map so the {@link app/components/MarkdownPipe} can link
 * `@decorator` tokens synchronously while rendering. A missing or malformed asset
 * leaves the registry empty, so the content renders as plain text.
 * @function loadDecoratorLinks
 * @returns {Promise<void>} Resolves once the registry is populated.
 * @memberOf module:app/seed/decorator-links
 */
export async function loadDecoratorLinks(): Promise<void> {
  try {
    const response = await fetch('assets/data/decorator-links.json');
    if (!response.ok) return;
    const data = (await response.json()) as DecoratorLinksAsset;
    if (data && typeof data === 'object' && data.decorators) {
      setDecoratorLinks(data.decorators);
    }
  } catch {
    // leave the registry empty; decorators render as plain text
  }
}
